### ISSUE TITLE
Throw warning when tibble(s) provided to codebook()/explorer()  

### ISSUE THREAD

**Issue by bzkrouse** [RhoInc/codebook#7]
Tibbles with list-columns will not render well in codebook/explorer.  Tibbles that are more or less a DF will work fine.  

For this reasons, we accept tibbles, but produce warning if tibble is provided in dataList/env 

Alternatively, we could ignore tibbles altogether and require pure DFs.

**Comment by jwildfire** [comment]
@bzkrouse Was this added in #14? If so, let's close the issue,

**Comment by bzkrouse** [comment]
@jwildfire Not yet.  We could add it to the next release
